import VideoView from '@/components/VideoView'

export default function VideoRoute({
  alternatePlayerLabel,
  buildVideoUrl,
  canNext,
  canPrev,
  goToLastPage,
  lastPage,
  totalItems,
  loading,
  onDeleteVideo,
  onOpenScreenshots,
  onOpenScrapeSettings,
  onSearchSubtitles,
  onSubtitleUpdated,
  onRenameVideo,
  onTagClick,
  onSelectAll,
  onSelectPage,
  onPlayPage,
  onPlayAll,
  bulkActionBusy,
  mpvEnabled,
  openAlternatePlayer,
  openPlayer,
  page,
  randomMode,
  revealFile,
  selectedVideoIds,
  setPage,
  setTagPickerFor,
  setVideoTempSort,
  toggleSelectVideo,
  videoGlobalSort,
  videoTempSort,
  videos,
  waterfallMode,
  onWaterfallModeChange,
  onLoadMore,
  loadingMore,
  hasMore,
}) {
  return (
    <VideoView
      page={page}
      lastPage={lastPage}
      totalItems={totalItems}
      canPrev={canPrev}
      canNext={canNext}
      loading={loading}
      randomMode={randomMode}
      videoTempSort={videoTempSort}
      videoGlobalSort={videoGlobalSort}
      buildVideoUrl={buildVideoUrl}
      setPage={setPage}
      setVideoTempSort={setVideoTempSort}
      goToLastPage={goToLastPage}
      videos={videos}
      selectedVideoIds={selectedVideoIds}
      toggleSelectVideo={toggleSelectVideo}
      onSelectAll={onSelectAll}
      onSelectPage={onSelectPage}
      onPlayPage={onPlayPage}
      onPlayAll={onPlayAll}
      bulkActionBusy={bulkActionBusy}
      mpvEnabled={mpvEnabled}
      openPlayer={openPlayer}
      openAlternatePlayer={openAlternatePlayer}
      revealFile={revealFile}
      alternatePlayerLabel={alternatePlayerLabel}
      setTagPickerFor={setTagPickerFor}
      onOpenScreenshots={onOpenScreenshots}
      onOpenScrapeSettings={onOpenScrapeSettings}
      onSearchSubtitles={onSearchSubtitles}
      onSubtitleUpdated={onSubtitleUpdated}
      onRenameVideo={onRenameVideo}
      onDeleteVideo={onDeleteVideo}
      onTagClick={onTagClick}
      waterfallMode={waterfallMode}
      onWaterfallModeChange={onWaterfallModeChange}
      onLoadMore={onLoadMore}
      loadingMore={loadingMore}
      hasMore={hasMore}
    />
  )
}
